### ISSUE TITLE
error in jinja2 init py

### ISSUE THREAD

**Issue by rbaradkar** [jjmontesl/cubetl#13]
I am getting this error while running it with cubetl -h 

Traceback (most recent call last):
  File "/var/www/html/cubetl/cub_env/bin/cubetl", line 9, in <module>
    load_entry_point('cubetl', 'console_scripts', 'cubetl')()
  File "/var/www/html/cubetl/cub_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/var/www/html/cubetl/cub_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/var/www/html/cubetl/cub_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/var/www/html/cubetl/cub_env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/var/www/html/cubetl/cubetl/core/bootstrap.py", line 36, in <module>
    from cubetl.util import config, log
  File "/var/www/html/cubetl/cubetl/util/config.py", line 27, in <module>
    from cubetl.template.jinja import JinjaTemplateRenderer
  File "/var/www/html/cubetl/cubetl/template/jinja.py", line 23, in <module>
    from jinja2 import Template
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/var/www/html/cubetl/cub_env/lib/python3.5/site-packages/Jinja2-3.0.0a1-py3.5.egg/jinja2/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/var/www/html/cubetl/cub_env/lib/python3.5/site-packages/Jinja2-3.0.0a1-py3.5.egg/jinja2/bccache.py", line 207
    dirname = f"_jinja2-cache-{os.getuid()}"
                                           ^
SyntaxError: invalid syntax

**Comment by rbaradkar** [comment]
I just uninstalled jinja 2 and reinstalled it and the error was gone
