### ISSUE TITLE
cubetl not working after successfully installation

### ISSUE THREAD

**Issue by ashutoshgaurav** [jjmontesl/cubetl#2]
After following each and every step as stated in the instructions,
not able to use the command "cubetl -h".
The following error is shown :

```
Traceback (most recent call last):
  File "/root/cubetl/env/bin/cubetl", line 11, in <module>
    load_entry_point('cubetl', 'console_scripts', 'cubetl')()
  File "/root/cubetl/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/cubetl/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/root/cubetl/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/root/cubetl/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/cubetl/cubetl/core/bootstrap.py", line 23, in <module>
    import importlib.util
ImportError: No module named util
```

**Comment by jjmontesl** [comment]
You are using Python 2.7 to run the project whereas CubETL requires Python 3.5+.

Check the README.md file, it shows how to create a virtual environment for Python 3.5:

```
# Using a virtualenv is usually recommended:
python3 -m venv env
. env/bin/activate
```
