### ISSUE TITLE
Unexpected error in examples/sql

### ISSUE THREAD

**Issue by dfrankow** [jjmontesl/cubetl#9]
I ran examples/sql/sql2olap.sh, then ran the cubes server, and got the error below. I don't know exactly which "Title" is the problem.

1. To replicate:

```
# Apply https://github.com/jjmontesl/cubetl/pull/8 to open port 5005
docker-compose run --service-ports cubetls /bin/bash
pip install cubes click flask
cd examples/sql
sh sql2olap.sh
# Edit chinook.cubes-config.ini to use host 0.0.0.0 to listen for connections outside docker
slicer serve chinook.cubes-config.ini >& slicer.log &
```

From outside the docker container, connect to http://localhost:5005/cube/Invoice/facts.

2. The error (from `slicer.log`):

```
2019-11-22 20:28:26,018 DEBUG Exception stack trace:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cubes/sql/query.py", line 575, in column
    column = table.columns[mapping.column]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: 'Title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/cubes/server/decorators.py", line 118, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cubes/server/decorators.py", line 167, in wrapper
    retval = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cubes/server/blueprint.py", line 414, in cube_facts
    page_size=g.page_size)
  File "/usr/local/lib/python3.7/site-packages/cubes/sql/browser.py", line 249, in facts
    include_fact_key=True)
  File "/usr/local/lib/python3.7/site-packages/cubes/sql/browser.py", line 486, in denormalized_statement
    context = self._create_context(context_attributes)
  File "/usr/local/lib/python3.7/site-packages/cubes/sql/browser.py", line 472, in _create_context
    safe_labels=self.safe_labels)
  File "/usr/local/lib/python3.7/site-packages/cubes/sql/query.py", line 883, in __init__
    bases = {attr:self.star_schema.column(attr) for attr in base_names}
  File "/usr/local/lib/python3.7/site-packages/cubes/sql/query.py", line 883, in <dictcomp>
    bases = {attr:self.star_schema.column(attr) for attr in base_names}
  File "/usr/local/lib/python3.7/site-packages/cubes/sql/query.py", line 579, in column
    % (mapping.column, mapping.table, avail))
cubes.sql.query.SchemaError: Unknown column 'Title' in table 'Invoice' possible: Invoice.InvoiceId, Invoice.CustomerId, Invoice.InvoiceDate, Invoice.BillingAddress, Invoice.BillingCity, Invoice.BillingState, Invoice.BillingCountry, Invoice.BillingPostalCode, Invoice.Total
```

**Comment by dfrankow** [comment]
I attach `chinook.cubes-model.json.txt` in case that helps. github doesn't allow .json, so I added .txt.  "Title" is all over, so it's not obvious to me what's happening.

```
$ grep Title examples/sql/chinook.cubes-model.json  | wc -l
      49
```

[chinook.cubes-model.json.txt](https://github.com/jjmontesl/cubetl/files/3881350/chinook.cubes-model.json.txt)

**Comment by dfrankow** [comment]
I took just the "Invoice" part of the model and put that in a file (attached).

There are only two titles in it:

```
$ grep Title invoice.json.txt 
                "CustomerId_SupportRepId_Title",
                "CustomerId_SupportRepId_Title.Title": "CustomerId_SupportRepId.Title",
```

[invoice.json.txt](https://github.com/jjmontesl/cubetl/files/3881369/invoice.json.txt)

**Comment by jjmontesl** [comment]
This works for me using Cubes master.  Please try if that solves your issue:

`pip install https://github.com/DataBrewery/cubes/archive/master.zip click flask --upgrade`

Cubes master includes a change I had to do to support aliased dimensions, but I was still facing some bugs in cubes which are difficult for me to debug. Ideally, my roadmap was to try and implement OLAP queries on CubETL and use it as a replacement for slicer in the future, since CubETL already has information about mappings and schema.

**Comment by jjmontesl** [comment]
BTW, last week I introduced a bug in master which prevents this example from working. I'm pushing a fix in a minute.

**Comment by dfrankow** [comment]
When I just tried master, it worked. Thanks.

I would suggest tagging a 1.1.1 or something, so a labeled version has the fix. But, it's not blocking me for anything, so it's not high priority.

I'll close this, and you can reopen if you need to.
